[project]
name = "sn-smarteda"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.1",
    "pandas>=3.0.0",
    "rich>=14.3.1",
    "scipy>=1.17.0",
    "seaborn>=0.13.2",
]
